# Generated by Django 5.0.3 on 2024-03-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('publishing_year', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('chapters', models.IntegerField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('cover', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
